// User
export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'
// Ticket
export const TICKETS_REQUEST_START = 'TICKET_REQUEST_START'
export const TICKETS_REQUEST_SUCCESS = 'TICKET_REQUEST_SUCCESS'
export const TICKETS_REQUEST_FAILURE = 'TICKET_REQUEST_FAILURE'
export const TICKET_INFO_SUCCESS = 'TICKET_INFO_SUCCESS'
